<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<!-- English translation for AstraScanner.
     This file is auto-generated by lupdate and manually edited.
     Run: cmake --build build --target update_translations
     to refresh from source code. -->

<context>
    <name>MainWindow</name>
    <message>
        <source>Файл</source>
        <translation>File</translation>
    </message>
    <message>
        <source>Правка</source>
        <translation>Edit</translation>
    </message>
    <message>
        <source>Экспорт</source>
        <translation>Export</translation>
    </message>
    <message>
        <source>Импорт</source>
        <translation>Import</translation>
    </message>
    <message>
        <source>Настройки</source>
        <translation>Settings</translation>
    </message>
    <message>
        <source>Отменить</source>
        <translation>Undo</translation>
    </message>
    <message>
        <source>Повторить</source>
        <translation>Redo</translation>
    </message>
    <message>
        <source>Главная</source>
        <translation>Home</translation>
    </message>
    <message>
        <source>Сканирование</source>
        <translation>Scanning</translation>
    </message>
    <message>
        <source>Калибровка</source>
        <translation>Calibration</translation>
    </message>
    <message>
        <source>Обработка</source>
        <translation>Processing</translation>
    </message>
    <message>
        <source>Проект</source>
        <translation>Project</translation>
    </message>
    <message>
        <source>Логи</source>
        <translation>Logs</translation>
    </message>
</context>

<context>
    <name>SettingsDialog</name>
    <message>
        <source>Настройки → Параметры</source>
        <translation>Settings → Parameters</translation>
    </message>
</context>

</TS>
